import { Pool } from 'pg'
import '../loadEnv.js'

const connectionString = process.env.DB_CONNECTION_STRING || process.env.POSTGRES_URL
const host = process.env.PGHOST || process.env.DB_HOST || 'localhost'
const port = Number(process.env.PGPORT || process.env.DB_PORT || 5432)
const database = process.env.PGDATABASE || process.env.DB_NAME || 'uptoskills'
const user = process.env.PGUSER || process.env.DB_USER || 'postgres'
const password = process.env.PGPASSWORD || process.env.DB_PASSWORD || ''

const poolConfig = {
  connectionString,
  host,
  port,
  database,
  user,
  password,
  max: 10,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000,
}

export const pool = new Pool(poolConfig)

export async function ensureDatabaseExists() {
  if (connectionString) return

  if (!/^[A-Za-z0-9_]+$/.test(database)) {
    throw new Error('DB_NAME can only contain letters, numbers, and underscores for automatic creation.')
  }

  const maintenancePool = new Pool({ ...poolConfig, database: 'postgres' })
  try {
    const { rows } = await maintenancePool.query('SELECT 1 FROM pg_database WHERE datname = $1', [database])
    if (rows.length === 0) {
      await maintenancePool.query(`CREATE DATABASE "${database}"`)
    }
  } finally {
    await maintenancePool.end()
  }

  await pool.query('SELECT 1')
}

/** Raw text-level query helper */
export const query = (text, params) => pool.query(text, params)

/** Returns all rows */
export const getAll = async (text, params) => {
  const { rows } = await pool.query(text, params)
  return rows
}

/** Returns a single row */
export const getOne = async (text, params) => {
  const { rows } = await pool.query(text, params)
  return rows[0] || null
}

/** Returns SQL value generated by an INSERT … RETURNING */
export const insert = async (text, params) => {
  const { rows } = await pool.query(text, params)
  return rows[0] || null
}

export default pool
